DROP TABLE IF EXISTS `ims_statistical_report`;
CREATE TABLE `ims_statistical_report`(
`id` INT AUTO_INCREMENT PRIMARY KEY,
`daily` VARCHAR(10) UNIQUE NOT NULL DEFAULT "" COMMENT "日期字符串",
`total_roamu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸截至昨日结束时间总用户数",
`total_rapltsu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "纯漫游鲸公众号截至昨日结束时间用户数",
`total_rminiu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "纯漫游鲸小程序截至昨日结束时间用户数",
`total_rplat_newu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游平台昨日新增用户数",
`total_roam_newu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸昨日新增用户数",
`total_raplts_newu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸公众号昨日新增用户数",
`total_saplt_newu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游共享店昨日新增用户数(去重)",
`total_rmini_newu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日新增用户数",
`total_raplts_fans` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸公众号截至昨日结束时间总粉丝数",
`total_raplts_newf` INT NOT NULL DEFAULT 0 COMMENT "漫游鲸公众号昨日新增粉丝数",
`total_raplts_newcf` INT NOT NULL DEFAULT 0 COMMENT "漫游鲸公众号昨日取关粉丝数",
`total_saplts_fans` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游共享店公众号截至昨日结束时间总粉丝数",
`total_saplts_newf` INT NOT NULL DEFAULT 0 COMMENT "漫游共享店公众号昨日新增粉丝数",
`total_saplts_newcf` INT NOT NULL DEFAULT 0 COMMENT "漫游共享店公众号昨日取关粉丝数",
`total_rmini_visitsu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序截至昨日结束时间总访问人数",
`total_rmini_newvistsuv` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日新增访问人数",
`total_rmini_newvistno` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日新增访问次数",
`total_rmini_newvistusr` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日新增用户数",
`total_rmini_newrcypageu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序回收页昨日访问人数",
`total_rmini_newrcypagen` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序回收页昨日访问次数",
`total_rmini_newbdepageu` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序商品详情页昨日访问人数",
`total_rmini_newbdepagen` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序商品详情页昨日访问次数",
`total_rmini_newvitstay` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日用户人均停留时长",
`total_rmini_newsearpv` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日搜索商品次数",
`total_rmini_newsearuv` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸小程序昨日搜索商品人数",
`total_rmini_newmeansear` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸小程序昨日人均搜索次数",
`total_rorder_newno` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸昨日销售订单数",
`total_rordgoods_newno` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸昨日销售商品数",
`mean_ordprice` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸昨日销售客单价",
`meam_ordgoods` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸昨日单均销量",
`conversion_ordrate` DECIMAL(10,4) NOT NULL DEFAULT 0.00 COMMENT "漫游鲸昨日销售转化率",
`ordernum_in24` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸24小时下单数",
`conversion_ordrate24` DECIMAL(10,4) NOT NULL DEFAULT 0.00 COMMENT "漫游鲸24小时销售转化率",
`mean_ordprice24`  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸24小时销售客单价",
`meam_ordgoods24`  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸24小时单均销量",
`totalrcy_rorder_newno` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸昨日回收订单数",
`totalrcy_rordgoods_newno` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸昨日回收商品数",
`meanrcy_ordprice`  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸昨日回收客单码洋",
`meamrcy_ordgoods`  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸昨日单均回收本数",
`conversion_rcyordrate` DECIMAL(10,4) NOT NULL DEFAULT 0.00 COMMENT "漫游鲸昨日回收转化率",
`rcyordernum_in24` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "漫游鲸24小时回收下单数",
`conversion_rcyordrate24` DECIMAL(10,4) NOT NULL DEFAULT 0.00 COMMENT "漫游鲸24小时回收转化率",
`mean_rcyordprice24`  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸24小时回收客单码洋",
`meam_rcyordgoods24`  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT "漫游鲸24小时单均回收本数",
`record_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "记录时间",
`operator` VARCHAR(32) NOT NULL DEFAULT "" COMMENT "操作者"
)ENGINE=INNODB DEFAULT CHARSET=UTF8;